# .swiftlint.yml

# 비활성화할 SwiftLint 규칙 목록
disabled_rules:
- trailing_whitespace
- identifier_name
- type_name
- force_cast
- shorthand_operator
- line_length
  - rule_name_to_disable
  - another_rule_to_disable

# SwiftLint에서 검사에서 제외할 디렉터리 또는 파일 목록
excluded:
- Sources/Application/AppDelegate.swift
- Sources/Application/SceneDelegate.swift
- "Tuist"
  
#included:
#  -

# 강제 형변환 사용 시 경고 설정
force_cast: warning

# 식별자 네이밍 규칙 설정
naming:
  min_length: 3
  max_length: 40
  # 제외할 식별자 목록
  excluded:
    - id
    - URL

# 파일 길이 규칙 설정
file_length:
  warning: 1000
  error: 2000

# 타입 이름 길이 규칙 설정
type_name:
  min_length: 2
  max_length: 40

# import 문 정렬 규칙 설정
sorted_imports: true
